USE [master]
GO

/****** Object:  Database [WebTask]    Script Date: 11/28/2015 15:52:04 ******/
CREATE DATABASE [WebTask] ON  PRIMARY 
GO

ALTER DATABASE [WebTask] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebTask].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebTask] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebTask] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebTask] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebTask] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebTask] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebTask] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebTask] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [WebTask] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebTask] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebTask] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebTask] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebTask] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebTask] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebTask] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebTask] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebTask] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebTask] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebTask] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebTask] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebTask] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebTask] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebTask] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebTask] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebTask] SET  READ_WRITE 
GO

ALTER DATABASE [WebTask] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WebTask] SET  MULTI_USER 
GO

ALTER DATABASE [WebTask] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebTask] SET DB_CHAINING OFF 
GO




USE [WebTask]
GO

/****** Object:  Table [dbo].[Orders]    Script Date: 11/28/2015 15:53:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Orders](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Price] [float] NOT NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [WebTask]
GO

/****** Object:  Table [dbo].[Languages]    Script Date: 11/28/2015 15:54:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Languages](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[EngName] [nvarchar](50) NOT NULL,
	[CultureName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Languages] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

--- insert default language data

insert into [dbo].[Languages] (EngName , Name, CultureName) values ('English','English','en-US');
insert into [dbo].[Languages] (EngName , Name, CultureName) values ('Arabic',N'عربى','ar-EG');